Repository Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022, pull requests merged in 2022-10, with the labels that each got.

#14 added controller to make a new project
  controllers/main.controllers.js
Labels: hacktoberfest-accepted, hacktoberfest, changes-requested

#12 Add: controller to delete client from database
  controllers/main.controllers.js
Labels: hacktoberfest-accepted, hacktoberfest, changes-requested

#13 Create get end point response for single client
  controllers/main.controllers.js
Labels: hacktoberfest-accepted, hacktoberfest, changes-requested

#20 Feature : Included PUT
  controllers/main.controllers.js
Labels: hacktoberfest-accepted, hacktoberfest, changes-requested

#21 Issue https://github.com/Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022/issues/11: Created GET request to get a single project data
  controllers/main.controllers.js
Labels: hacktoberfest-accepted, hacktoberfest

#24 created contribute.md
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, changes-requested
